services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - catalogo
      - deudas
      - pagos
      - reportes
  auth:
    build: ./auth
    ports:
      - "3001:3000"
  catalogo:
    build: ./catalogo
    ports:
      - "3002:3000"
  deudas:
    build: ./deudas
    ports:
      - "3003:3000"
    depends_on:
      - deudas_db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@deudas_db:5432/deudasdb
  pagos:
    build: ./pagos
    ports:
      - "3004:3000"
  reportes:
    build: ./reportes
    ports:
      - "3005:3000"
  deudas_db:
    image: postgres:16-alpine
    container_name: deudas_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deudasdb