# Generated by Django 6.0.5 on 2026-05-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(max_length=50)),
                ('service_id', models.CharField(max_length=50)),
                ('customer_ref', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('receipt_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
