# Generated by Django 6.0.4 on 2026-04-30 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0003_companymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='provider', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_tenancy.companymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_tenancy.usermodel')),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
    ]
